Algoritmo "Media"
// Descrição: Dê três notas, some elas e realize a divisão.
// Autor(a): Letícia Freitas
// Data atual: 20/01/2023
Var
n1, n2, n3, soma, divisao: real

Inicio
escreval ("insira o primeiro valor: "
leia (n1)
escreval ("insira o segundo valor: ")
leia (n2)
escreval ("insira o terceiro valor: "
leia (n3)
soma <- n1 + n2 + n3 / 3
escreval ("a média entre os três valores é:", soma)

Fimalgoritmo