Algoritmo "Somatória"
// Autor(a): Letícia Freitas
// Data atual: 06/02/2023
// Faça um algoritmo que receba cinco números inteiros,
// imprima a soma dos cinco valores.

Var
cont,num,soma:inteiro

Inicio
soma<-0
       PARA cont<- 1 ATE 5 FACA
       escreval("Digite um número: ")
       leia(num)
       soma<-soma+num
       FIMPARA
              escreval("A soma dos valores: ",soma)
Fimalgoritmo
