Algoritmo "Olá Mundo"
// Descrição: Aqui você descreve o que o programa faz! (função)
// Autor(a): Letícia Freitas
// Data atual: 20/01/2023

Var
// Seção de Declarações das variáveis 
msg: caractere
nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
msg <- "Olá Mundo!"
escrevaL (msg)
nome <- "Letícia Fr."
Escreva("Muito prazer ", nome)

Fimalgoritmo