Algoritmo "Subtração"
// Descrição: Solicitar dois números para
// o usuário e mostrar a subtração de um pelo outro.
// Autor(a): Letícia Freitas.
// Data atual: 20/01/2023

Var
n1, n2, subtracao: inteiro
Inicio
Escreva ("Digite um número: ")
Leia(n1)
Escreva ("Digite outro número: ")
leia (n2)
subtracao <-n1 - n2
EscrevaL ("A subtração de um número pelo outro é: ", subtracao)

Fimalgoritmo